"""initial schema

Revision ID: 08d2f4a8b684
Revises: 
Create Date: 2026-09-02 08:08:11.883520
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '08d2f4a8b684'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'uploader', 'reviewer', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)

    op.create_table('batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_name'), ['name'], unique=False)

    op.create_table('checklist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('checklist_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=128), nullable=False),
    sa.Column('min_pages', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_items_checklist_id'), ['checklist_id'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('patient_ref', sa.String(length=128), nullable=False),
    sa.Column('encounter_ref', sa.String(length=128), nullable=False),
    sa.Column('checklist_id', sa.String(length=36), nullable=True),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'encounter_ref', name='uq_case_batch_encounter')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_encounter_ref'), ['encounter_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_patient_ref'), ['patient_ref'], unique=False)

    op.create_table('completeness_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('findings_json', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('completeness_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_completeness_results_case_id'), ['case_id'], unique=True)

    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingest_status', sa.Enum('pending', 'running', 'completed', 'failed', 'rejected', 'password_protected', 'corrupted', name='ingeststatus'), nullable=False),
    sa.Column('ingest_error', sa.Text(), nullable=True),
    sa.Column('storage_key_original', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_ingest_status'), ['ingest_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_uploaded_at'), ['uploaded_at'], unique=False)

    op.create_table('logical_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('source_page_index', sa.Integer(), nullable=False),
    sa.Column('spread_half', sa.String(length=8), nullable=False),
    sa.Column('printed_page_label', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'ordinal', name='uq_page_doc_ordinal')
    )
    with op.batch_alter_table('logical_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logical_pages_document_id'), ['document_id'], unique=False)

    op.create_table('page_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('logical_page_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('replaces_version_id', sa.String(length=36), nullable=True),
    sa.Column('storage_key_render', sa.String(length=512), nullable=False),
    sa.Column('storage_key_thumb', sa.String(length=512), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('dpi_estimate', sa.Integer(), nullable=True),
    sa.Column('colour_mode', sa.Enum('colour', 'grey', 'bitonal', name='colourmode'), nullable=False),
    sa.Column('capture_profile', sa.Enum('flatbed', 'photo', 'unknown', name='captureprofile'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['logical_page_id'], ['logical_pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logical_page_id', 'version_no', name='uq_version_page_no')
    )
    with op.batch_alter_table('page_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_versions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_versions_logical_page_id'), ['logical_page_id'], unique=False)
        batch_op.create_index('ix_pv_active', ['logical_page_id', 'is_active'], unique=False)

    op.create_table('diagnosis_extractions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'extracted_pending_review', 'not_found', 'unreadable', 'uncertain', 'processing_failed', 'unconfigured', name='diagnosisstatus'), nullable=False),
    sa.Column('anchor_label', sa.String(length=128), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=False),
    sa.Column('qualifier', sa.Enum('final', 'provisional', 'suspected', 'differential', 'ruled_out', 'negated', 'past_history', 'unspecified', name='qualifier'), nullable=False),
    sa.Column('icd_code_verbatim', sa.String(length=64), nullable=True),
    sa.Column('is_handwritten', sa.Boolean(), nullable=False),
    sa.Column('region_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('provider_used', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_version_id'], ['page_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnosis_extractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_extractions_page_version_id'), ['page_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_extractions_status'), ['status'], unique=False)

    op.create_table('handwriting_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('detected', 'none_detected', 'failed', 'unconfigured', 'pending', name='handwritingstatus'), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('provider_used', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_version_id'], ['page_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('handwriting_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handwriting_results_page_version_id'), ['page_version_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_handwriting_results_status'), ['status'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('ingest', 'quality', 'handwriting', 'diagnosis', name='jobkind'), nullable=False),
    sa.Column('state', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='jobstate'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('page_version_id', sa.String(length=36), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['page_version_id'], ['page_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_job_idem')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_page_version_id'), ['page_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_queued_at'), ['queued_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_state'), ['state'], unique=False)

    op.create_table('page_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_version_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_version_id'], ['page_versions.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_reviews_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_reviews_page_version_id'), ['page_version_id'], unique=False)

    op.create_table('quality_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_version_id', sa.String(length=36), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('thresholds_hash', sa.String(length=64), nullable=False),
    sa.Column('overall', sa.Enum('unchecked', 'acceptable', 'review', 'rescan', 'blank', 'failed', name='pageclass'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('provider_used', sa.String(length=64), nullable=True),
    sa.Column('provider_error', sa.Text(), nullable=True),
    sa.Column('raw_metrics_json', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_version_id'], ['page_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_results_overall'), ['overall'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_results_page_version_id'), ['page_version_id'], unique=True)

    op.create_table('diagnosis_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('extraction_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('corrected_qualifier', sa.Enum('final', 'provisional', 'suspected', 'differential', 'ruled_out', 'negated', 'past_history', 'unspecified', name='qualifier'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['diagnosis_extractions.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnosis_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_reviews_extraction_id'), ['extraction_id'], unique=False)

    op.create_table('handwriting_regions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('handwriting_result_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('note', 'signature', 'stamp', 'tick', 'correction', 'uncertain', name='handwritingcategory'), nullable=False),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('script_hint', sa.String(length=32), nullable=False),
    sa.Column('polygon_json', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['handwriting_result_id'], ['handwriting_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('handwriting_regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handwriting_regions_handwriting_result_id'), ['handwriting_result_id'], unique=False)

    op.create_table('quality_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quality_result_id', sa.String(length=36), nullable=False),
    sa.Column('defect_code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='severity'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('region_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['quality_result_id'], ['quality_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_findings_defect_code'), ['defect_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_findings_quality_result_id'), ['quality_result_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_findings_quality_result_id'))
        batch_op.drop_index(batch_op.f('ix_quality_findings_defect_code'))

    op.drop_table('quality_findings')
    with op.batch_alter_table('handwriting_regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handwriting_regions_handwriting_result_id'))

    op.drop_table('handwriting_regions')
    with op.batch_alter_table('diagnosis_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosis_reviews_extraction_id'))

    op.drop_table('diagnosis_reviews')
    with op.batch_alter_table('quality_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_results_page_version_id'))
        batch_op.drop_index(batch_op.f('ix_quality_results_overall'))

    op.drop_table('quality_results')
    with op.batch_alter_table('page_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_reviews_page_version_id'))
        batch_op.drop_index(batch_op.f('ix_page_reviews_action'))

    op.drop_table('page_reviews')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_state'))
        batch_op.drop_index(batch_op.f('ix_jobs_queued_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_page_version_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))

    op.drop_table('jobs')
    with op.batch_alter_table('handwriting_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handwriting_results_status'))
        batch_op.drop_index(batch_op.f('ix_handwriting_results_page_version_id'))

    op.drop_table('handwriting_results')
    with op.batch_alter_table('diagnosis_extractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosis_extractions_status'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_extractions_page_version_id'))

    op.drop_table('diagnosis_extractions')
    with op.batch_alter_table('page_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_pv_active')
        batch_op.drop_index(batch_op.f('ix_page_versions_logical_page_id'))
        batch_op.drop_index(batch_op.f('ix_page_versions_is_active'))

    op.drop_table('page_versions')
    with op.batch_alter_table('logical_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logical_pages_document_id'))

    op.drop_table('logical_pages')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_documents_ingest_status'))
        batch_op.drop_index(batch_op.f('ix_documents_case_id'))
        batch_op.drop_index(batch_op.f('ix_documents_batch_id'))

    op.drop_table('documents')
    with op.batch_alter_table('completeness_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_completeness_results_case_id'))

    op.drop_table('completeness_results')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_patient_ref'))
        batch_op.drop_index(batch_op.f('ix_cases_encounter_ref'))
        batch_op.drop_index(batch_op.f('ix_cases_batch_id'))

    op.drop_table('cases')
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_items_checklist_id'))

    op.drop_table('checklist_items')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_name'))
        batch_op.drop_index(batch_op.f('ix_batches_created_at'))

    op.drop_table('batches')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('checklists')
    # ### end Alembic commands ###
