"""add prescription analysis tables

Revision ID: 3f2938b32f54
Revises: 08d2f4a8b684
Create Date: 2026-09-04 12:17:21.144420
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '3f2938b32f54'
down_revision = '08d2f4a8b684'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescription_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'extracted_pending_review', 'not_a_prescription', 'unreadable', 'processing_failed', 'unconfigured', name='prescriptionstatus'), nullable=False),
    sa.Column('language_detected', sa.String(length=64), nullable=True),
    sa.Column('raw_extracted_text', sa.Text(), nullable=False),
    sa.Column('diagnosis_or_notes', sa.Text(), nullable=False),
    sa.Column('possible_interpretation', sa.Text(), nullable=False),
    sa.Column('patient_explanation', sa.Text(), nullable=False),
    sa.Column('safety_warnings_json', sa.JSON(), nullable=False),
    sa.Column('uncertainties_json', sa.JSON(), nullable=False),
    sa.Column('requires_professional_confirmation', sa.Boolean(), nullable=False),
    sa.Column('ocr_provider_used', sa.String(length=64), nullable=True),
    sa.Column('reasoning_provider_used', sa.String(length=64), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_version_id'], ['page_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescription_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_analyses_page_version_id'), ['page_version_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_prescription_analyses_status'), ['status'], unique=False)

    op.create_table('prescription_medicines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dose', sa.String(length=128), nullable=False),
    sa.Column('frequency', sa.String(length=128), nullable=False),
    sa.Column('duration', sa.String(length=128), nullable=False),
    sa.Column('general_use', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('uncertainty', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['prescription_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescription_medicines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_medicines_analysis_id'), ['analysis_id'], unique=False)

    # Adding a value to an existing PostgreSQL native ENUM type needs ALTER TYPE ... ADD VALUE, not
    # a column type change (which the autogenerated diff proposed — that would try to CREATE TYPE
    # jobkind again and fail, since it already exists). SQLite has no real enum type to alter; the
    # Enum() column there is a CHECK constraint that SQLAlchemy already treats loosely enough that
    # a new Python-side JobKind value works without a schema change.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TYPE jobkind ADD VALUE IF NOT EXISTS 'prescription'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL cannot drop a single value from an existing enum type without rebuilding it
    # wholesale (and any job rows already using it), so downgrade leaves 'prescription' in the
    # jobkind enum. It is inert once the tables below are gone — nothing can reference it.

    with op.batch_alter_table('prescription_medicines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_medicines_analysis_id'))

    op.drop_table('prescription_medicines')
    with op.batch_alter_table('prescription_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_analyses_status'))
        batch_op.drop_index(batch_op.f('ix_prescription_analyses_page_version_id'))

    op.drop_table('prescription_analyses')
    # ### end Alembic commands ###
